### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by neosin** [socialigniter/socialigniter#46]
There is a folder missing. This is the error I get after running install.php

Your system folder path does not appear to be set correctly. 
Please open the following file and correct this: index.php

I open the index.php and it is looking for a folder "../system"

this folder does not exist in the archive for socialigniter.
Is there something missing?

**Comment by bnvk** [comment]
So sorry about that. I moved the "system" folder which is the core CodeIgniter files one directory higher so that I can have multiple installs of Social-Igniter on the same host with a smaller footprint. Those core CI files now live at https://github.com/socialigniter/system I've also updated the README instructions to reflect this. Thanks for the issue :)
